#!/usr/bin/env ansible-playbook

- name: install ambari agents
  hosts: hdp
  gather_facts: yes
  become: yes
  vars_files:
    - ./vars/main.yml
  tasks:
    - systemd: name=ambari-agent state=restarted enabled=yes

