#!/usr/bin/env ansible-playbook
---
- name: create ec2 key pairs
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./vars/ec2.yml 
  tasks:
    - name: create key
      ec2_key: name="{{ key_name }}" region="{{ region }}"
      register: keypair
      
    - name: write key to file
      copy: dest=files/ec2-key.pem content="{{ keypair.key.private_key  }}" mode=0400
      when: keypair.changed
