#!/usr/bin/env ansible-playbook
---
- name: create and fetch certificates
  hosts: ranger
  gather_facts: no
  become: yes
  vars_files:
    - ./vars/ranger.yml
  roles:
    - hdp-ranger-create-certs

- name: deploy ranger certs for hadoop
  hosts: hadoop
  become: yes
  vars_files:
    - ./vars/ranger.yml
  roles:
    - { role: hdp-ranger-deploy-certs, service: hadoop }

- name: deploy ranger certs for atlas
  hosts: atlas
  become: yes
  vars_files:
    - ./vars/ranger.yml
  roles:
    - { role: hdp-ranger-deploy-certs, service: atlas }
    
    
- name: deploy ranger certs for nimbus
  hosts: nimbus
  become: yes
  vars_files:
    - ./vars/ranger.yml
  roles:
    - { role: hdp-ranger-deploy-certs, service: storm }


- name: deploy ranger certs for knox
  hosts: knox
  become: yes
  vars_files:
    - ./vars/ranger.yml
  roles:
    - { role: hdp-ranger-deploy-certs, service: knox }


- name: deploy ranger certs for kafka
  hosts: kafka
  become: yes
  vars_files:
    - ./vars/ranger.yml
  roles:
    - { role: hdp-ranger-deploy-certs, service: kafka }

- name: deploy ranger certs for hive
  hosts: hiveserver
  become: yes
  vars_files:
    - ./vars/ranger.yml
  roles:
    - { role: hdp-ranger-deploy-certs, service: hive }

- name: deploy ranger certs for hbase
  hosts: hbase
  become: yes
  vars_files:
    - ./vars/ranger.yml
  roles:
    - { role: hdp-ranger-deploy-certs, service: hbase }
