krb_realm: FIELD.HORTONWORKS.COM
kdc_hostnames:
  - ad01.field.hortonworks.com
  - ad02.field.hortonworks.com
kdc_admin_hostnames:
  - ad01.field.hortonworks.com
  - ad02.field.hortonworks.com
krb_domain: field.hortonworks.com
domain_ou: "OU=HadoopNodes,DC=field,DC=hortonworks,DC=com"
login_ccache: "/tmp/krb5cc_0"
sssd_user: registersssd
