#!/usr/bin/env ansible-playbook
---
- name: bootstrap hosts for the hadoop installation
  hosts: hdp
  gather_facts: yes
  become: yes
  vars_files:
    - ./vars/main.yml
  roles:
    - hadoop-bootstrap

- name: install ambari agents
  hosts: hdp
  gather_facts: yes
  become: yes
  vars_files:
    - ./vars/main.yml
  roles:
    - hdp-ambari-agents
    
- name: enable sssd
  hosts: hdp
  gather_facts: yes
  become: yes
  vars_files:
    - ./vars/security.yml
    - ./hiddenvars/security.yml
  roles:
    - hdp-security

- name: install mysql server
  hosts: utility
  gather_facts: yes
  become: yes
  vars_files:
    - ./vars/mysql.yml
  roles:
    - hdp-mysql-server

- name: install ambari-server
  hosts: utility
  gather_facts: yes
  become: yes
  vars_files:
    - ./vars/main.yml
    - ./vars/mysql.yml
  roles:
    - hdp-ambari-server
